name: pep-edit-st
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - rdkit
  - openmm
  - openff-toolkit
  - openff-nagl
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - MDAnalysis
  - scipy
  - cmcrameri
  - cython
  - pip
  - pip:
    - pdb_numpy
    - git+https://github.com/samuelmurail/SST2.git
