name: pep-edit-st
channels:
  - conda-forge
  - nodefaults
  - nvidia
dependencies:
  - python
  - rdkit
  - openmm
  - cuda-toolkit
  - openmmforcefields
  - openff-toolkit <= 13.0.0
  - openff-nagl
  - pdbfixer
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - MDAnalysis
  - scipy
  - cmcrameri
  - cython
  - pip
  - pip:
    - pdb_numpy
    - git+https://github.com/samuelmurail/SST2.git
